### ISSUE TITLE
Default Branch + Read Me

### ISSUE THREAD

**Issue by isabellabrookes** [PixelogicDev/Gruvee#19]
When you go to the repo, you don't get the beautiful Readme

I feel you should make Release 1.0 the default for now (all the commits too) but you can decide how you're doing this 😄

**Comment by adilanchian** [comment]
Hey!

Yaaaaa I've been thinking about this... The problem is I still want the base branch to be master. If we change the base branch to be release-1.0, then all of our branch mappings may get out of wack =/. I think to combat this, I'm going to add the README to master. I want out pretty README to be front and center!

**Comment by adilanchian** [comment]
Ended up just merging the latest from `release-1.0` into `master`! Thanks!
